### ISSUE TITLE
Transfer to organisation

### ISSUE THREAD

**Issue by mike42** [receipt-print-hq/escpos-printer-db#12]
I'd like to action a suggestion by @patkan at python-escpos/python-escpos#149, to transfer this repository to an organisation. This will help facilitate community maintenance.

I've created an empty organisation which is named so that it could host any community-maintained receipt printing code: https://github.com/receipt-print-hq

Is this name suitable, or would you prefer something else? ('Receipt printer HQ', 'Receipt printers HQ', 'Receipt printing HQ', 'Thermal Printers R Us' etc.)

If there's no other suggestions or objection, I'll transfer this repository to receipt-print-hq around September 7th, 2016.

**Comment by patkan** [comment]
:+1:
The name is good.

**Comment by mike42** [comment]
Transferred.

Aside, I've also forked it back to my own name so that I don't break python-escpos. I'll leave this issue open until I've posted a pull request to update the submodule URL.
