### ISSUE TITLE
Zjiang Zj-5890T profile

### ISSUE THREAD

**Issue by mike42** [receipt-print-hq/escpos-printer-db#13]
This is a very common printer for people starting out with receipt printing, as it is very cheap! It has 58mm width with support for only a few commands.

The `simple` profile works well, but the test print suggests that the printer has very good code page support that can be added:

![2016-09-zj5890-testprint](https://cloud.githubusercontent.com/assets/2080552/18228993/f14c5f6e-72a8-11e6-9dfc-d44b1ffe6367.png)

A manual came with the printer which I haven't found on the manufacturer's site, but may contain more detailed info. ("58MM thermal printer
Programming Manual" / 58MMPrinter Programmer Manual-20150312.pdf)

**Comment by miracle2k** [comment]
I bought this printer, because I wanted to experiment with arabic printing. Maybe I can make some progress on the profile, too.

**Comment by mike42** [comment]
My [StackOverflow answer to "Print Arabic words from Python to ESC/POS printer?"](http://stackoverflow.com/questions/38683686/print-arabic-words-from-python-to-esc-pos-printer) may help you out here. I've never been able to get Arabic text working natively, only by rendering to an image.

**Comment by za3k** [comment]
Some additional info on capabilities
-All bar codes, linear and QR, in the output samples fail. (I stopped testing after these)
-Graphics command fails
-Bit image command works (but "wide" and "tall" tux are identical to regular tux)
-Text sizes work, but they're not monotonically bigger--they stay the same or wrap around early. Sorry, don't have a scanner to show the precise output here

**Comment by mike42** [comment]
Thanks for sharing @za3k, this is consistent with what I've seen.

**Comment by mike42** [comment]
Profile will be available downstream as `POS-5890` in the next releases of the respective projects.
